#ifndef CANFILTER_USB_H
#define CANFILTER_USB_H

// canfilter_usb
//
// Provides a USB transport layer for uploading a completed CAN filter
// configuration to a supported USB-connected device. This class handles
// device discovery, optional serial-number filtering, capability queries,
// and transfer of the filter image generated by a canfilter_* builder.
//
// Key features:
//   • open() methods locate and connect to the device using VID/PID and optional serial
//   • hasHardwareFilter() and getFilterInfo() query device capabilities
//   • programFilter() uploads a prebuilt hw_config buffer to the device
//
// This class does not perform any filter computation or translation. It is
// strictly a transport and management layer that delivers hardware-ready
// filter data to the device.

#include "usb_device.hpp"

class canfilter_usb : public usb_device {
  public:
    canfilter_usb() = default;
    ~canfilter_usb() override = default;

    bool open();                                                    // uses our vid/pid list
    bool open(uint16_t vid, uint16_t pid, std::string serial = ""); // uses vid/pid and optional serial.

    bool hasHardwareFilter();
    uint32_t getFilterInfo();
    bool programFilter(const void *config, uint32_t size);

  private:
    const std::vector<std::pair<uint16_t, uint16_t>> default_vid_pid_list_ = {
        {0x1D50, 0x606F},
        {0x1209, 0xCA01},
    };
};

#endif
